// Local-only integration fixture. Never included in public/ or used in deployment.
import {PGlite} from '@electric-sql/pglite';import {createServer} from 'node:http';import {readFile} from 'node:fs/promises';import {randomUUID} from 'node:crypto';
const db=new PGlite();await db.exec(`create role anon;create role authenticated;create schema auth;create function auth.uid() returns uuid language sql as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth to authenticated;grant execute on function auth.uid() to authenticated;`);await db.exec(await readFile('supabase/baseline.sql','utf8'));await db.exec(await readFile('supabase/upgrade.sql','utf8'));
const types={html:'text/html',css:'text/css',js:'text/javascript',json:'application/json'};let queue=Promise.resolve();
createServer((req,res)=>{queue=queue.then(async()=>{try{let raw='';for await(const c of req)raw+=c;const u=new URL(req.url,'http://localhost');
res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Access-Control-Allow-Headers','*');res.setHeader('Cache-Control','no-store');
if(req.method==='OPTIONS'){res.end();return;}
if(u.pathname==='/config.js'){res.setHeader('Content-Type','text/javascript');res.end(`export const SUPABASE_URL=location.origin;export const SUPABASE_ANON_KEY='local-test-key';`);return;}
if(u.pathname.startsWith('/auth/v1/')){const id=randomUUID(),user={id,aud:'authenticated',role:'authenticated',is_anonymous:true,email:''};const token='eyJhbGciOiJIUzI1NiJ9.'+Buffer.from(JSON.stringify({sub:id,role:'authenticated',exp:Math.floor(Date.now()/1000)+3600})).toString('base64url')+'.test';res.setHeader('Content-Type','application/json');res.end(JSON.stringify({user,access_token:token,refresh_token:id,expires_in:3600,token_type:'bearer'}));return;}
if(u.pathname.startsWith('/rest/v1/rpc/')){const name=u.pathname.split('/').pop();if(!/^[a-z_]+$/.test(name))throw Error('Invalid RPC');const id=JSON.parse(Buffer.from(req.headers.authorization.split('.')[1],'base64url')).sub;const args=JSON.parse(raw||'{}');const keys=Object.keys(args);if(keys.some(k=>!/^p_[a-z_]+$/.test(k)))throw Error('Invalid argument');await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);await db.exec('set role authenticated');const {rows}=await db.query(`select * from public.${name}(${keys.map((k,i)=>k+'=>$'+(i+1)).join(',')})`,Object.values(args));res.setHeader('Content-Type','application/json');res.end(JSON.stringify(rows.length===1&&Object.hasOwn(rows[0],name)?rows[0][name]:rows));return;}
const path=u.pathname==='/'?'index.html':u.pathname.slice(1);if(path.includes('..'))throw Error('Invalid path');res.setHeader('Content-Type',types[path.split('.').pop()]||'application/octet-stream');res.end(await readFile('public/'+path));
}catch(e){res.statusCode=400;res.setHeader('Content-Type','application/json');res.end(JSON.stringify({message:e.message}));}});}).listen(Number(process.env.CAMBIO_PREVIEW_PORT||4173),'127.0.0.1',()=>console.log('Local integration preview running'));
