import {PGlite} from '@electric-sql/pglite';import {readFileSync} from 'node:fs';import assert from 'node:assert/strict';
const db=new PGlite();await db.exec(`create role anon;create role authenticated;create schema auth;create function auth.uid() returns uuid language sql as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;`);await db.exec(readFileSync('supabase/baseline.sql','utf8'));
const a='00000000-0000-0000-0000-000000000001',b='00000000-0000-0000-0000-000000000002';await db.query("select set_config('request.jwt.claim.sub',$1,false)",[a]);const code=(await db.query("select public.create_room('Upgrade test') r")).rows[0].r.room_code;await db.query("select set_config('request.jwt.claim.sub',$1,false)",[b]);await db.query("select public.join_room($1,'Second player')",[code]);await db.query("select set_config('request.jwt.claim.sub',$1,false)",[a]);await db.query('select public.start_game($1)',[code]);
await db.query("update public.game_cards set rank='J' where id=(select id from public.game_cards where room_code=$1 and zone='deck' order by deck_order limit 1)",[code]);await db.query('select public.draw_card($1)',[code]);await db.query("select public.resolve_draw($1,'discard',null)",[code]);
const before=(await db.query('select id,room_code,zone,owner_user_id,position,rank,suit,deck_order from public.game_cards order by id')).rows;
await db.exec(readFileSync('supabase/upgrade.sql','utf8'));
assert.deepEqual((await db.query('select id,room_code,zone,owner_user_id,position,rank,suit,deck_order from public.game_cards order by id')).rows,before);
const v=(await db.query('select public.get_game_view($1) v',[code])).rows[0].v;assert.equal(v.room.status,'playing');assert.equal(v.game.phase,'ability');assert.equal(v.ability,'blind_swap');assert(v.players.every(p=>p.first_turn_started));await db.query('select public.blind_swap($1,0,$2,0)',[code,b]);assert.equal((await db.query('select current_turn_user_id from public.game_state where room_code=$1',[code])).rows[0].current_turn_user_id,b);
console.log('PASS: upgrade preserves live room, every card, current turn and pending power; play continues');await db.close();
